name: Environment variable
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:  
      - name: Get the code
        uses: actions/checkout@v4.2.2
      - name: Install NodeJS
        uses: actions/setup-node@v3  
      - name: Configure environment variables
        run: echo "MY_VARIABLE=Hello from GHA" >> $GITHUB_ENV
      - name: Run code
        run: node main.js
