name: Hello World
on:
  workflow_dispatch:    
  # push:
  #   branches:
  #     - main
  # schedule:
  #   - cron: "*/5 * * * *" 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      - name: Print greeting
        run: echo "Hello world"
      - name: Another task
        run: echo "Another task"    
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: List the files of the repo
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree

