name: Hello World
on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *" 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      - name: Print greeting
        run: echo "Hello world"
      - name: Another task
        run: echo "Amother task"
