name: Issues example
on:
  issues:
    types: 
      - opened
jobs:
  process-issue:
    runs-on: ubuntu-latest
    steps:  
      - name: Display issue's title
        run: |
          echo "The title of the issue is: ${{github.event.issue.title}}"
