name: Manual trigger
on:
  workflow_dispatch:
    inputs:
      text:
        description: Label of a text field
        required: true
      build:
        description: Build type
        type: choice
        default: release
        options: [release, debug]
jobs:        
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display the inputs
        run: |
          echo "Label: ${{ github.inputs.text }}"
          echo "Build type: ${{ github.inputs.build }}"
