name: Multiple jobs
on:
  workflow_dispatch:
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print job's name
        run: echo "Job 1"
  job-2:
    runs-on: macos-latest
    steps:
      - name: Print job's name
        run: echo "Job 2"
  job-3:
    runs-on: windows-latest
    steps:
      - name: Print job's name
        run: echo "Job 3"        
  job-4:
    runs-on: ubuntu-latest
    needs: [job-1,job-3]
    steps:
      - name: Print completion message
        run: echo "Waited on Job-1 & Job-3. Job-4 completed"     
