name: Variables & secrets
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Printing variables & secrets
        run: |
          echo "MY_REPO_VARIABLE: ${{ vars.MY_REPO_VARIABLE }}"
          echo "CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}"
