name: Variables & secrets
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Printing variables & secrets
        run: |
          echo "MY_REPO_VARIABLE: ${{ vars.MY_REPO_VARIABLE }}"
          echo "CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}"
      - name: Get the code
        uses: actions/checkout@v4.2.2 
      - name: Install NodeJS
        uses: actions/setup-node@v3        
      - name: Run JS code
        env: 
          MY_REPO_VARIABLE: ${{ vars.MY_REPO_VARIABLE }}
        run: node variables.js    
    
