name: Workflow commands
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display warning & error
        run: |
          echo "::warning::Warning message"
          echo "::error::Error message"
